<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oc_platform.bigbrother.message_notificator' shared service.

return $this->services['oc_platform.bigbrother.message_notificator'] = new \OC\PlatformBundle\Bigbrother\MessageNotificator(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->getSwiftmailer_Mailer_DefaultService()) && false ?: '_'});
