<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNmeobgb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNmeobgb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNmeobgb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNmeobgb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNmeobgb\appProdProjectContainer(array(
    'container.build_hash' => 'Nmeobgb',
    'container.build_id' => 'b6dcecc6',
    'container.build_time' => 1534920083,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNmeobgb');
