<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oc_platform.twig.antispam_extension' shared service.

return $this->services['oc_platform.twig.antispam_extension'] = new \OC\PlatformBundle\Twig\AntispamExtension(${($_ = isset($this->services['oc_platform.antispam']) ? $this->services['oc_platform.antispam'] : $this->load('getOcPlatform_AntispamService.php')) && false ?: '_'});
