<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oc_platform.purger.advert' shared service.

return $this->services['oc_platform.purger.advert'] = new \OC\PlatformBundle\PurgerPlatform\OCPurgerPlatform(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
