<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oc_platform.bigbrother.message_listener' shared service.

return $this->services['oc_platform.bigbrother.message_listener'] = new \OC\PlatformBundle\Bigbrother\MessageListener(${($_ = isset($this->services['oc_platform.bigbrother.message_notificator']) ? $this->services['oc_platform.bigbrother.message_notificator'] : $this->load('getOcPlatform_Bigbrother_MessageNotificatorService.php')) && false ?: '_'}, array(0 => 'alexandre', 1 => 'marine', 2 => 'pierre'));
