<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2rxp8b9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2rxp8b9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2rxp8b9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2rxp8b9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2rxp8b9\appDevDebugProjectContainer(array(
    'container.build_hash' => '2rxp8b9',
    'container.build_id' => '7a103ed7',
    'container.build_time' => 1534926921,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2rxp8b9');
